name: offset_iterator_nucleus
description: Helper functions for using offset_iterator with the nucleus package
version: 0.1.0
homepage: https://github.com/tim-smart/offset_iterator

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0

dependencies:
  elemental: ^0.2.0
  nucleus: ^0.4.1
  offset_iterator: ^0.1.0
