name: offset_iterator_io
description: Extension methods for offset_iterator, for working with dart:io and friends.
version: 0.1.0
homepage: https://github.com/tim-smart/offset_iterator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  elemental: ^0.2.0
  offset_iterator: ^0.1.0

dev_dependencies:
  benchmarking: ^0.6.1
  flutter_lints: ^4.0.0
  test: any
