name: offset_iterator_io
description: Extension methods for offset_iterator, for working with dart:io and friends.
version: 0.0.3
homepage: https://github.com/tim-smart/offset_iterator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fpdart: ^0.0.12
  offset_iterator: ^0.0.37

dev_dependencies:
  benchmarking: ^0.6.1
  flutter_lints: ^1.0.0
  test: any
