name: offset_iterator_persist
description: Persistence extension for offset_iterator
version: 0.0.7
homepage: https://github.com/tim-smart/offset_iterator

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  fast_immutable_collections: ^7.0.3
  flutter:
    sdk: flutter
  fpdart: ^0.0.12
  hive: ^2.0.4
  offset_iterator: ^0.0.45
  path_provider: ^2.0.7
  shared_preferences: ^2.0.9
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
