name: offset_iterator_persist
description: Persistence extension for offset_iterator
version: 0.1.0
homepage: https://github.com/tim-smart/offset_iterator

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  elemental: ^0.2.0
  flutter:
    sdk: flutter
  hive: ^2.0.4
  offset_iterator: ^0.1.0
  path_provider: ^2.0.7
  shared_preferences: ^2.0.9
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
