name: offset_iterator
description: Pull based async iterator with offset tracking. An alternative to Stream.
version: 0.1.0
homepage: https://github.com/tim-smart/offset_iterator

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  elemental: ^0.2.0

dev_dependencies:
  benchmarking: ^0.6.1
  flutter_lints: ^4.0.0
  rxdart: ^0.28.0
  test: any
