name: offset_iterator
description: Pull based async iterator with offset tracking. An alternative to Stream.
version: 0.0.62
homepage: https://github.com/tim-smart/offset_iterator

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  fast_immutable_collections: ^7.0.3
  fpdt: ^0.0.29

dev_dependencies:
  benchmarking: ^0.6.1
  flutter_lints: ^1.0.0
  rxdart: ^0.27.3
  test: any
