name: offset_iterator
description: Pull based async iterator with offset tracking
version: 0.0.8
homepage: https://github.com/tim-smart/offset_iterator

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  fast_immutable_collections: ^7.0.3
  fpdart: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  rxdart: ^0.27.3
