name: state_iterator
description: A special kind of OffsetIterator, designed for managing state in an application.
version: 0.0.4
homepage: https://github.com/tim-smart/offset_iterator

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  fpdart: ^0.0.12
  offset_iterator: ^0.0.49

dev_dependencies:
  flutter_lints: ^1.0.0
  test: any
