name: state_iterator
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tim-smart/offset_iterator

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  fpdart: ^0.0.12
  offset_iterator: ^0.0.47

dev_dependencies:
  flutter_lints: ^1.0.0
  test: any
