name: offset_iterator_builder
description: A flutter widget builder for the offset_iterator package.
version: 0.1.0
homepage: https://github.com/tim-smart/offset_iterator

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  elemental: ^0.2.0
  offset_iterator: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
