name: offset_iterator_riverpod
description: Helper functions for creating RiverPod providers for OffsetIterator's.
version: 0.0.8
homepage: https://github.com/tim-smart/offset_iterator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  offset_iterator: ^0.0.32
  riverpod: ^1.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
