name: offset_iterator_riverpod
description: Helper functions for creating RiverPod providers for OffsetIterator's.
version: 0.0.24
homepage: https://github.com/tim-smart/offset_iterator

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  fpdt: ^0.1.0
  offset_iterator: ^0.0.62
  riverpod: ^1.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  test: any
